include $(GOROOT)/src/Make.inc

DIRS=\
	protocol\
	server\
	transport\

TARG=thrift
GOFILES=\
	thrift.go\
	tprotocol.go\
	ttransport.go\
	tserver.go\

-include Make.deps

include $(GOROOT)/src/Make.pkg